
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed backgroundFixed;
	
	private global::Gtk.Frame frame2;
	
	private global::Gtk.Alignment GtkAlignment1;
	
	private global::Gtk.ScrolledWindow dataScroll;
	
	private global::Gtk.TextView textView;
	
	private global::Gtk.Label GtkLabel2;
	
	private global::Gtk.Frame frame3;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.Fixed fixed4;
	
	private global::Gtk.Entry feedUrlEntry;
	
	private global::Gtk.Label feedUrlLabel;
	
	private global::Gtk.CheckButton uploadCheckbox;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.Label feedErrorLabel;
	
	private global::Gtk.Label GtkLabel3;
	
	private global::Gtk.Frame deviceFrame;
	
	private global::Gtk.Alignment GtkAlignment2;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Label deviceErrorLabel;
	
	private global::Gtk.Label GtkLabel5;
	
	private global::Gtk.Frame frame5;
	
	private global::Gtk.Alignment GtkAlignment3;
	
	private global::Gtk.Fixed fixed5;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Entry uploadUrlEntry;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.Label uploadLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 600;
		this.HeightRequest = 400;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultHeight = 400;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.backgroundFixed = new global::Gtk.Fixed ();
		this.backgroundFixed.WidthRequest = 605;
		this.backgroundFixed.HeightRequest = 400;
		this.backgroundFixed.Name = "backgroundFixed";
		this.backgroundFixed.HasWindow = false;
		// Container child backgroundFixed.Gtk.Fixed+FixedChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.WidthRequest = 190;
		this.frame2.HeightRequest = 380;
		this.frame2.Name = "frame2";
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.dataScroll = new global::Gtk.ScrolledWindow ();
		this.dataScroll.TooltipMarkup = "Overview of data collected from scouts";
		this.dataScroll.Name = "dataScroll";
		this.dataScroll.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.dataScroll.ShadowType = ((global::Gtk.ShadowType)(1));
		this.dataScroll.BorderWidth = ((uint)(5));
		// Container child dataScroll.Gtk.Container+ContainerChild
		this.textView = new global::Gtk.TextView ();
		this.textView.CanFocus = true;
		this.textView.Name = "textView";
		this.textView.Editable = false;
		this.textView.WrapMode = ((global::Gtk.WrapMode)(1));
		this.dataScroll.Add (this.textView);
		this.GtkAlignment1.Add (this.dataScroll);
		this.frame2.Add (this.GtkAlignment1);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Data Overview</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel2;
		this.backgroundFixed.Add (this.frame2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.backgroundFixed [this.frame2]));
		w4.X = 5;
		w4.Y = 5;
		// Container child backgroundFixed.Gtk.Fixed+FixedChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.WidthRequest = 200;
		this.frame3.HeightRequest = 190;
		this.frame3.Name = "frame3";
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.feedUrlEntry = new global::Gtk.Entry ();
		this.feedUrlEntry.TooltipMarkup = "http://thebluealliance.com/####XXXX";
		this.feedUrlEntry.WidthRequest = 170;
		this.feedUrlEntry.CanFocus = true;
		this.feedUrlEntry.Name = "feedUrlEntry";
		this.feedUrlEntry.Text = global::Mono.Unix.Catalog.GetString ("2016utwv");
		this.feedUrlEntry.IsEditable = true;
		this.feedUrlEntry.InvisibleChar = '•';
		this.fixed4.Add (this.feedUrlEntry);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.feedUrlEntry]));
		w5.Y = 25;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.feedUrlLabel = new global::Gtk.Label ();
		this.feedUrlLabel.Name = "feedUrlLabel";
		this.feedUrlLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("TBA Competition Name");
		this.fixed4.Add (this.feedUrlLabel);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.feedUrlLabel]));
		w6.X = 5;
		w6.Y = 5;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.uploadCheckbox = new global::Gtk.CheckButton ();
		this.uploadCheckbox.TooltipMarkup = "Upload match xml when retrieving data from the device";
		this.uploadCheckbox.CanFocus = true;
		this.uploadCheckbox.Name = "uploadCheckbox";
		this.uploadCheckbox.Label = global::Mono.Unix.Catalog.GetString ("Upload to Device");
		this.uploadCheckbox.DrawIndicator = true;
		this.uploadCheckbox.UseUnderline = true;
		this.fixed4.Add (this.uploadCheckbox);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.uploadCheckbox]));
		w7.Y = 55;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button ();
		this.button3.TooltipMarkup = "Pulls match data from TheBlueAlliance";
		this.button3.WidthRequest = 170;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Download Feed Data");
		this.fixed4.Add (this.button3);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.button3]));
		w8.Y = 80;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.feedErrorLabel = new global::Gtk.Label ();
		this.feedErrorLabel.WidthRequest = 170;
		this.feedErrorLabel.Name = "feedErrorLabel";
		this.feedErrorLabel.Xalign = 0F;
		this.fixed4.Add (this.feedErrorLabel);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.feedErrorLabel]));
		w9.Y = 150;
		this.GtkAlignment.Add (this.fixed4);
		this.frame3.Add (this.GtkAlignment);
		this.GtkLabel3 = new global::Gtk.Label ();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Feed</b>");
		this.GtkLabel3.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel3;
		this.backgroundFixed.Add (this.frame3);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.backgroundFixed [this.frame3]));
		w12.X = 395;
		w12.Y = 5;
		// Container child backgroundFixed.Gtk.Fixed+FixedChild
		this.deviceFrame = new global::Gtk.Frame ();
		this.deviceFrame.WidthRequest = 190;
		this.deviceFrame.HeightRequest = 380;
		this.deviceFrame.Name = "deviceFrame";
		// Container child deviceFrame.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.TooltipMarkup = "Get scouting data from the device";
		this.button1.WidthRequest = 160;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Pull From Device");
		this.fixed2.Add (this.button1);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.button1]));
		w13.Y = 5;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.deviceErrorLabel = new global::Gtk.Label ();
		this.deviceErrorLabel.WidthRequest = 160;
		this.deviceErrorLabel.Name = "deviceErrorLabel";
		this.deviceErrorLabel.Xalign = 0F;
		this.fixed2.Add (this.deviceErrorLabel);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.deviceErrorLabel]));
		w14.Y = 340;
		this.GtkAlignment2.Add (this.fixed2);
		this.deviceFrame.Add (this.GtkAlignment2);
		this.GtkLabel5 = new global::Gtk.Label ();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Device</b>");
		this.GtkLabel5.UseMarkup = true;
		this.deviceFrame.LabelWidget = this.GtkLabel5;
		this.backgroundFixed.Add (this.deviceFrame);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.backgroundFixed [this.deviceFrame]));
		w17.X = 200;
		w17.Y = 5;
		// Container child backgroundFixed.Gtk.Fixed+FixedChild
		this.frame5 = new global::Gtk.Frame ();
		this.frame5.WidthRequest = 200;
		this.frame5.HeightRequest = 190;
		this.frame5.Name = "frame5";
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Upload URL");
		this.fixed5.Add (this.label3);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label3]));
		w18.X = 5;
		w18.Y = 5;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.uploadUrlEntry = new global::Gtk.Entry ();
		this.uploadUrlEntry.TooltipMarkup = "url to the stats website";
		this.uploadUrlEntry.WidthRequest = 170;
		this.uploadUrlEntry.CanFocus = true;
		this.uploadUrlEntry.Name = "uploadUrlEntry";
		this.uploadUrlEntry.Text = global::Mono.Unix.Catalog.GetString ("http://2468.meshiest.com/");
		this.uploadUrlEntry.IsEditable = true;
		this.uploadUrlEntry.InvisibleChar = '•';
		this.fixed5.Add (this.uploadUrlEntry);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.uploadUrlEntry]));
		w19.Y = 25;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button ();
		this.button2.TooltipMarkup = "Upload the scouting match data to stats website";
		this.button2.WidthRequest = 170;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Upload New Data");
		this.fixed5.Add (this.button2);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.button2]));
		w20.Y = 60;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button ();
		this.button4.WidthRequest = 170;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Upload All Data");
		this.fixed5.Add (this.button4);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.button4]));
		w21.Y = 95;
		this.GtkAlignment3.Add (this.fixed5);
		this.frame5.Add (this.GtkAlignment3);
		this.uploadLabel = new global::Gtk.Label ();
		this.uploadLabel.Name = "uploadLabel";
		this.uploadLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Upload</b>");
		this.uploadLabel.UseMarkup = true;
		this.frame5.LabelWidget = this.uploadLabel;
		this.backgroundFixed.Add (this.frame5);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.backgroundFixed [this.frame5]));
		w24.X = 395;
		w24.Y = 195;
		this.Add (this.backgroundFixed);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 600;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button3.Clicked += new global::System.EventHandler (this.downloadFeed);
		this.button1.Clicked += new global::System.EventHandler (this.attemptFind);
		this.button2.Clicked += new global::System.EventHandler (this.uploadNew);
		this.button4.Clicked += new global::System.EventHandler (this.uploadAll);
	}
}
